name: Autoupdate CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2    
      - name: Perform autoupdate
        run: ./autoupdate.sh
