name: Autoupdate CI
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2    
      - name: Perform autoupdate
        run: ./autoupdate.sh    
      - name: Push updates
        run: |
          git config --global user.name 'Alessandro Pomponio'
          git config --global user.email '10339005+AlessandroPomponio@users.noreply.github.com'
          git commit -am "[AUTO] Update to latest TDlib build"
          git push
